language: go

go: 1.8.3

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

install:
  - go get ./...
  # Install gometalinter and certain linters
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - gometalinter
  - go test ./... -timeout 30s

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
