language: go

go: 1.10.x

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

install:
  - go get ./...
  # Install gometalinter and certain linters
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - gometalinter --disable-all -E vet -E gofmt -E misspell -E ineffassign -E goimports -E deadcode --tests ./...
  - go test ./... -timeout 30s

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
